
// TABLE ACTION TYPE
export const ADD_TABLE = "ADD_TABLE"
export const DELETE_TABLE = "DELETE_TABLE"
export const REPLACE_TABLE = "REPLACE_TABLE"

// MENU ACTION TYPE
export const ADD_MENU = "ADD_MENU"
export const DELETE_MENU = "DELETE_MENU"
export const REPLACE_MENU = "REPLACE_MENU"

// CUSTOMER ACTION TYPE
export const ADD_CUSTOMER = "ADD_CUSTOMER"
export const DELETE_CUSTOMER = "DELETE_CUSTOMER"
export const REPLACE_CUSTOMER = "REPLACE_CUSTOMER"

// FORM ACTION TYPE
export const CHANGE_FORM = "CHANGE_FORM"
export const CHANGE_FORM_ERROR = "CHANGE_FORM_ERROR"
export const CLEAR_FORM = "CLEAR_FORM"
export const REPLACE_FORM = "REPLACE_FORM"
export const SET_LOADING_FORM = "SET_LOADING_FORM"

// AUTH ACTION TYPE
export const SET_AUTH = "SET_AUTH"

// PRODUCT ACTION TYPE
export const ADD_PRODUCT = "ADD_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const REPLACE_PRODUCT = "REPLACE_PRODUCT"
export const SET_LOADING_PRODUCT = "SET_LOADING_PRODUCT"